CREATE TABLE `short_video` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `platform` tinyint(1) DEFAULT '0' COMMENT '视频平台',
  `uuid` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '视频id',
  `title` varchar(1024) DEFAULT '' COMMENT '视频标题',
  `width` smallint(11) DEFAULT '0' COMMENT '视频宽度',
  `height` smallint(11) DEFAULT '0' COMMENT '视频高度',
  `duration` mediumint(11) DEFAULT '0' COMMENT '视频长度',
  `thumbnail_uri` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '图片url',
  `video_uri` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '视频url',
  `share_uri` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '视频分享url',
  `preview_uri` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '视频预览url',
  `liked_num` int(11) DEFAULT '0' COMMENT 'like数',
  `loop_num` int(11) DEFAULT '0' COMMENT '循环数',
  `view_num` int(11) DEFAULT '0' COMMENT '观看数',
  `comment_num` int(11) DEFAULT '0' COMMENT '评论数',
  `share_num` int(11) DEFAULT '0' COMMENT '分享数',
  `avg_view_time` int(11) DEFAULT '0' COMMENT '平均观看时间',
  `user_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'user id',
  `user_nick_name` varchar(64) DEFAULT '' COMMENT 'nick name',
  `user_real_name` varchar(64) DEFAULT '' COMMENT 'user name',
  `user_display_name` varchar(64) DEFAULT '' COMMENT 'user name',
  `user_icon` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '' COMMENT '头像地址',
  `user_desc` varchar(1024) DEFAULT '' COMMENT '描述',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_platform` (`platform`)
) ENGINE=InnoDB AUTO_INCREMENT=8843 DEFAULT CHARSET=utf8mb4;